import XCTest
@testable import RiseOn

/// Covers task.md S7.1-S7.4. The bull/bear/consolidation fixtures and their
/// expected fields were **not hand-computed** — they were generated by
/// actually running `stock_analyzer.py::StockTrendAnalyzer` (copied
/// verbatim into a standalone script, only swapping the `get_config()` call
/// for its literal default `bias_threshold=5.0`) on these exact bars, in a
/// real pandas session, then transcribed. The Swift logic itself was
/// additionally cross-checked by transliterating it to Python and running
/// it against the same fixtures before this file was written, to catch
/// translation bugs ahead of a real Swift compiler being available.
///
/// NOTE on fixture design: the bull/bear series use *accelerating*
/// growth/decay, not constant-ratio growth. An earlier constant-ratio
/// attempt put the STRONG_BULL-vs-BULL "is the MA5/MA20 spread widening"
/// comparison within ~1e-10 of its own boundary — close enough that
/// floating-point summation order (pandas' internal rolling-window
/// algorithm vs. a straightforward recompute) could flip the result. That's
/// not a logic bug, just a fragile fixture; accelerating growth gives the
/// comparison several percentage points of margin instead.
final class RuleScoreEngineTests: XCTestCase {

    /// `XCTAssertEqual(_:_:accuracy:)` only exists for `FloatingPoint`
    /// scalars, not arrays — this does the element-wise version for
    /// `[Double]` (used for `supportLevels`/`resistanceLevels`).
    private func assertDoubleArrayEqual(
        _ actual: [Double],
        _ expected: [Double],
        accuracy: Double = 1e-6,
        file: StaticString = #file,
        line: UInt = #line
    ) {
        XCTAssertEqual(actual.count, expected.count, "count mismatch", file: file, line: line)
        for (a, e) in zip(actual, expected) {
            XCTAssertEqual(a, e, accuracy: accuracy, file: file, line: line)
        }
    }

    // MARK: - S7.1: enums

    func test_enums_haveExactlyTheExpectedCases() {
        XCTAssertEqual(TrendStatus.allCases.count, 7)
        XCTAssertEqual(VolumeStatus.allCases.count, 5)
        XCTAssertEqual(BuySignal.allCases.count, 6)
        XCTAssertEqual(MACDStatus.allCases.count, 7)
        XCTAssertEqual(RSIStatus.allCases.count, 5)
    }

    func test_enums_rawValuesMatchPythonEnumValues() {
        XCTAssertEqual(TrendStatus.strongBull.rawValue, "强势多头")
        XCTAssertEqual(TrendStatus.strongBear.rawValue, "强势空头")
        XCTAssertEqual(VolumeStatus.shrinkVolumeDown.rawValue, "缩量回调")
        XCTAssertEqual(BuySignal.strongBuy.rawValue, "强烈买入")
        XCTAssertEqual(MACDStatus.goldenCrossZero.rawValue, "零轴上金叉")
        XCTAssertEqual(RSIStatus.oversold.rawValue, "超卖")
    }

    // MARK: - Fixtures (verified against real stock_analyzer.py output)

    private let bullCloses: [Double] = [10.0, 10.05, 10.10829, 10.175004714, 10.2502997489, 10.3343522068, 10.4273613767, 10.5295495182, 10.6411627431, 10.7624719983, 10.8937741567, 11.0353932208, 11.1876816472, 11.3510217993, 11.525827535, 11.712545941, 11.911659222, 12.1236867562, 12.3491873298, 12.588761564, 12.8430545476, 13.1127586931, 13.3986168326, 13.7014255731, 14.0220389315, 14.3613722736, 14.7204065805, 15.1001930702, 15.5018582059, 15.9266091207, 16.3757394979, 16.8506359434, 17.3527848945, 17.8837801123, 18.4453308078, 19.0392704598, 19.667566385, 20.3323301288, 21.0358287513, 21.780497089]
    private let bullHighs: [Double] = [10.1, 10.1505, 10.2093729, 10.2767547611, 10.3528027464, 10.4376957289, 10.5316349905, 10.6348450134, 10.7475743705, 10.8700967183, 11.0027118983, 11.145747153, 11.2995584637, 11.4645320172, 11.6410858103, 11.8296714004, 12.0307758142, 12.2449236237, 12.4726792031, 12.7146491797, 12.9714850931, 13.2438862801, 13.532603001, 13.8384398288, 14.1622593208, 14.5049859964, 14.8676106463, 15.2511950009, 15.656876788, 16.0858752119, 16.5394968929, 17.0191423028, 17.5263127434, 18.0626179134, 18.6297841159, 19.2296631644, 19.8642420488, 20.5356534301, 21.2461870388, 21.9983020599]
    private let bullLows: [Double] = [9.9, 9.9495, 10.0072071, 10.0732546669, 10.1477967514, 10.2310086848, 10.3230877629, 10.424254023, 10.5347511156, 10.6548472784, 10.7848364152, 10.9250392886, 11.0758048307, 11.2375115813, 11.4105692596, 11.5954204816, 11.7925426298, 12.0024498886, 12.2256954565, 12.4628739484, 12.7146240022, 12.9816311062, 13.2646306643, 13.5644113173, 13.8818185422, 14.2177585509, 14.5732025147, 14.9491911395, 15.3468396238, 15.7673430295, 16.211982103, 16.682129584, 17.1792570456, 17.7049423111, 18.2608774997, 18.8488777552, 19.4708907211, 20.1290068275, 20.8254704637, 21.5626921182]
    private let bullVolumes: [Double] = [10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 6000.0, 5800.0, 5600.0, 5400.0, 5200.0, 5000.0]

    private let bearCloses: [Double] = [20.0, 19.9, 19.78458, 19.654001772, 19.5085621589, 19.3485919492, 19.1744546216, 18.9865449663, 18.7852875897, 18.5711353112, 18.3445674604, 18.1060880834, 17.8562240679, 17.5955231965, 17.3245521392, 17.0438943946, 16.7541481899, 16.4559243521, 16.1498441591, 15.8365371825, 15.5166391314, 15.1907897096, 14.8596304939, 14.5238028448, 14.1839458582, 13.8406943684, 13.4946770092, 13.1465143424, 12.7968170609, 12.4461842734, 12.0952018769, 11.7444410225, 11.39445668, 11.0457863056, 10.6989486156, 10.3544424702, 10.0127458687, 9.6743150583, 9.3395837573, 9.0089624923]
    private let bearHighs: [Double] = [20.2, 20.099, 19.9824258, 19.8505417897, 19.7036477805, 19.5420778687, 19.3661991679, 19.176410416, 18.9731404656, 18.7568466643, 18.528013135, 18.2871489642, 18.0347863085, 17.7714784284, 17.4977976606, 17.2143333385, 16.9216896718, 16.6204835956, 16.3113426007, 15.9949025543, 15.6718055227, 15.3426976067, 15.0082267989, 14.6690408732, 14.3257853168, 13.9791013121, 13.6296237793, 13.2779794858, 12.9247852315, 12.5706461162, 12.2161538957, 11.8618854327, 11.5084012468, 11.1562441687, 10.8059381018, 10.4579868949, 10.1128733274, 9.7710582089, 9.4329795949, 9.0990521172]
    private let bearLows: [Double] = [19.8, 19.701, 19.5867342, 19.4574617543, 19.3134765373, 19.1551060297, 18.9827100754, 18.7966795167, 18.5974347138, 18.3854239581, 18.1611217858, 17.9250272026, 17.6776618272, 17.4195679645, 17.1513066178, 16.8734554506, 16.586606708, 16.2913651086, 15.9883457176, 15.6781718106, 15.3614727401, 15.0388818125, 14.711034189, 14.3785648163, 14.0421063996, 13.7022874248, 13.3597302391, 13.015049199, 12.6688488903, 12.3217224307, 11.9742498581, 11.6269966123, 11.2805121132, 10.9353284425, 10.5919591294, 10.2508980455, 9.91261841, 9.5775719077, 9.2461879197, 8.9188728674]
    private let bearVolumes: [Double] = [10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 16000.0, 16500.0, 17000.0, 17500.0, 18000.0, 18500.0]

    private let consolidationCloses: [Double] = [14.0, 14.05, 14.1, 14.15, 14.2, 14.25, 14.3, 14.35, 14.4, 14.45, 14.5, 14.55, 14.6, 14.65, 14.7, 14.75, 14.8, 14.85, 14.9, 14.95, 15.0, 15.05, 15.1, 15.15, 15.2, 15.25, 15.3, 15.35, 15.4, 15.45, 15.0, 15.0, 15.0, 15.0, 15.0, 15.0, 15.0, 15.0, 15.0, 15.0]
    private let consolidationHighs: [Double] = [14.14, 14.1905, 14.241, 14.2915, 14.342, 14.3925, 14.443, 14.4935, 14.544, 14.5945, 14.645, 14.6955, 14.746, 14.7965, 14.847, 14.8975, 14.948, 14.9985, 15.049, 15.0995, 15.15, 15.2005, 15.251, 15.3015, 15.352, 15.4025, 15.453, 15.5035, 15.554, 15.6045, 15.15, 15.15, 15.15, 15.15, 15.15, 15.15, 15.15, 15.15, 15.15, 15.15]
    private let consolidationLows: [Double] = [13.86, 13.9095, 13.959, 14.0085, 14.058, 14.1075, 14.157, 14.2065, 14.256, 14.3055, 14.355, 14.4045, 14.454, 14.5035, 14.553, 14.6025, 14.652, 14.7015, 14.751, 14.8005, 14.85, 14.8995, 14.949, 14.9985, 15.048, 15.0975, 15.147, 15.1965, 15.246, 15.2955, 14.85, 14.85, 14.85, 14.85, 14.85, 14.85, 14.85, 14.85, 14.85, 14.85]

    private func makeBars(closes: [Double], highs: [Double], lows: [Double], volumes: [Double]) -> [DailyBar] {
        (0..<closes.count).map { i in
            DailyBar(date: "d\(i)", open: closes[i], close: closes[i], high: highs[i], low: lows[i], volume: volumes[i])
        }
    }

    // MARK: - S7.2/S7.3: full-field parity, one case per trend category

    func test_bullFixture_matchesReferenceStockAnalyzer() {
        let bars = makeBars(closes: bullCloses, highs: bullHighs, lows: bullLows, volumes: bullVolumes)
        let result = RuleScoreEngine.analyze(bars: bars, code: "600519")

        XCTAssertEqual(result.trendStatus, .strongBull)
        XCTAssertEqual(result.trendStrength, 90, accuracy: 1e-6)
        XCTAssertEqual(result.ma5, 20.371098562775867, accuracy: 1e-6)
        XCTAssertEqual(result.ma10, 18.876376406978192, accuracy: 1e-6)
        XCTAssertEqual(result.ma20, 16.572604894934223, accuracy: 1e-6)
        XCTAssertEqual(result.ma60, 16.572604894934223, accuracy: 1e-6, "MA60 == MA20 column, <60 bars")
        XCTAssertEqual(result.biasMA5, 6.918618168409756, accuracy: 1e-6)
        XCTAssertEqual(result.biasMA10, 15.384947934143511, accuracy: 1e-6)
        XCTAssertEqual(result.biasMA20, 31.42470497020308, accuracy: 1e-6)
        XCTAssertEqual(result.volumeStatus, .normal)
        XCTAssertEqual(result.volumeRatio5d, 0.8928571428571429, accuracy: 1e-6)
        XCTAssertFalse(result.supportMA5)
        XCTAssertFalse(result.supportMA10)
        assertDoubleArrayEqual(result.supportLevels, [16.572604894934223])
        assertDoubleArrayEqual(result.resistanceLevels, [21.9983020599])
        XCTAssertEqual(result.macdDIF, 2.325824758276905, accuracy: 1e-6)
        XCTAssertEqual(result.macdDEA, 1.8774136655682263, accuracy: 1e-6)
        XCTAssertEqual(result.macdBar, 0.8968221854173577, accuracy: 1e-6)
        XCTAssertEqual(result.macdStatus, .bullish)
        XCTAssertEqual(result.rsi6, 100.0, accuracy: 1e-6)
        XCTAssertEqual(result.rsi12, 100.0, accuracy: 1e-6)
        XCTAssertEqual(result.rsi24, 100.0, accuracy: 1e-6)
        XCTAssertEqual(result.rsiStatus, .overbought)
        XCTAssertEqual(result.buySignal, .hold)
        XCTAssertEqual(result.signalScore, 58)
    }

    func test_bearFixture_matchesReferenceStockAnalyzer() {
        let bars = makeBars(closes: bearCloses, highs: bearHighs, lows: bearLows, volumes: bearVolumes)
        let result = RuleScoreEngine.analyze(bars: bars, code: "000001")

        XCTAssertEqual(result.trendStatus, .strongBear)
        XCTAssertEqual(result.trendStrength, 10, accuracy: 1e-6)
        XCTAssertEqual(result.ma5, 9.678009929342391, accuracy: 1e-6)
        XCTAssertEqual(result.ma10, 10.536888414730239, accuracy: 1e-6)
        XCTAssertEqual(result.ma20, 12.26842896197916, accuracy: 1e-6)
        XCTAssertEqual(result.ma60, 12.26842896197916, accuracy: 1e-6)
        XCTAssertEqual(result.biasMA5, -6.913068305869278, accuracy: 1e-6)
        XCTAssertEqual(result.biasMA10, -14.500731737047781, accuracy: 1e-6)
        XCTAssertEqual(result.biasMA20, -26.567920634356412, accuracy: 1e-6)
        XCTAssertEqual(result.volumeStatus, .normal)
        XCTAssertEqual(result.volumeRatio5d, 1.088235294117647, accuracy: 1e-6)
        XCTAssertFalse(result.supportMA5)
        XCTAssertFalse(result.supportMA10)
        XCTAssertEqual(result.supportLevels, [], "price is far below every MA, no support triggers")
        assertDoubleArrayEqual(result.resistanceLevels, [15.6718055227])
        XCTAssertEqual(result.macdDIF, -2.003004645674963, accuracy: 1e-6)
        XCTAssertEqual(result.macdDEA, -1.8430055583607288, accuracy: 1e-6)
        XCTAssertEqual(result.macdBar, -0.3199981746284686, accuracy: 1e-6)
        XCTAssertEqual(result.macdStatus, .bearish)
        XCTAssertEqual(result.rsi6, 0.0, accuracy: 1e-6)
        XCTAssertEqual(result.rsi12, 0.0, accuracy: 1e-6)
        XCTAssertEqual(result.rsi24, 0.0, accuracy: 1e-6)
        XCTAssertEqual(result.rsiStatus, .oversold)
        XCTAssertEqual(result.buySignal, .wait, "score==30 -> WAIT, not STRONG_SELL (score check wins before trend check)")
        XCTAssertEqual(result.signalScore, 30)
    }

    func test_consolidationFixture_matchesReferenceStockAnalyzer() {
        let bars = makeBars(closes: consolidationCloses, highs: consolidationHighs, lows: consolidationLows, volumes: Array(repeating: 10_000, count: 40))
        let result = RuleScoreEngine.analyze(bars: bars, code: "300059")

        XCTAssertEqual(result.trendStatus, .consolidation, "exact MA5==MA10 tie (flat tail) is the only way to reach the else-branch")
        XCTAssertEqual(result.trendStrength, 50, accuracy: 1e-6)
        XCTAssertEqual(result.ma5, 15.0, accuracy: 1e-6)
        XCTAssertEqual(result.ma10, 15.0, accuracy: 1e-6)
        XCTAssertEqual(result.ma20, 15.1125, accuracy: 1e-6)
        XCTAssertEqual(result.ma60, 15.1125, accuracy: 1e-6)
        XCTAssertEqual(result.biasMA5, 0.0, accuracy: 1e-6)
        XCTAssertEqual(result.biasMA10, 0.0, accuracy: 1e-6)
        XCTAssertEqual(result.biasMA20, -0.7444168734491362, accuracy: 1e-6)
        XCTAssertEqual(result.volumeStatus, .normal)
        XCTAssertTrue(result.supportMA5)
        XCTAssertTrue(result.supportMA10)
        // MA10 dedups against MA5 (both == 15.0); MA20 (15.1125) doesn't
        // qualify since price (15.0) < MA20 -> only one entry here.
        assertDoubleArrayEqual(result.supportLevels, [15.0])
        assertDoubleArrayEqual(result.resistanceLevels, [15.6045])
        XCTAssertEqual(result.macdStatus, .bullish)
        XCTAssertEqual(result.rsiStatus, .neutral)
        XCTAssertEqual(result.buySignal, .hold)
        XCTAssertEqual(result.signalScore, 63)
    }

    // MARK: - S7.3: MA20 support has no dedup (plan.md §0.5-5) — faithful, not "fixed"

    func test_supportLevels_ma20AppendHasNoDedup_producesLiteralDuplicate() {
        // Last 20 bars flat at 15.0 -> MA5 == MA10 == MA20 == 15.0 exactly.
        // MA5 appends 15.0. MA10 finds it already present, skips (dedup).
        // MA20's append has NO "already in list" guard in the Python source
        // (stock_analyzer.py:472-473) -- so it appends 15.0 again, producing
        // a literal duplicate. This is a faithful port of that asymmetry,
        // not a bug being "fixed" here.
        let ramp = (0..<20).map { 14.0 + 0.05 * Double($0) }
        let flat = Array(repeating: 15.0, count: 20)
        let closes = ramp + flat
        let bars = closes.map { DailyBar(date: "d", open: $0, close: $0, high: $0 + 0.1, low: $0 - 0.1, volume: 10_000) }

        let result = RuleScoreEngine.analyze(bars: bars, code: "DUPTEST")

        XCTAssertEqual(result.ma5, 15.0, accuracy: 1e-9)
        XCTAssertEqual(result.ma10, 15.0, accuracy: 1e-9)
        XCTAssertEqual(result.ma20, 15.0, accuracy: 1e-9)
        XCTAssertTrue(result.supportMA5)
        XCTAssertTrue(result.supportMA10)
        XCTAssertEqual(result.supportLevels, [15.0, 15.0], "verified against real stock_analyzer.py: it produces this exact duplicate too")
    }

    // MARK: - S7.4: stop-loss fallback

    func test_stopLossFallback_returnsFirstSupportLevel() {
        var result = RuleScore(code: "600519")
        result.supportLevels = [123.4, 456.7]
        XCTAssertEqual(RuleScoreEngine.stopLossFallback(for: result), 123.4)
    }

    func test_stopLossFallback_nilWhenNoSupportLevels() {
        let result = RuleScore(code: "600519")
        XCTAssertNil(RuleScoreEngine.stopLossFallback(for: result))
    }

    // MARK: - Guards

    func test_fewerThan20Bars_returnsInsufficientDataResult() {
        let bars = (0..<19).map { i in DailyBar(date: "d\(i)", open: 10, close: 10, high: 10.1, low: 9.9, volume: 100) }
        let result = RuleScoreEngine.analyze(bars: bars, code: "600519")

        XCTAssertEqual(result.riskFactors, ["数据不足，无法完成分析"])
        // Everything else should still be at RuleScore's own defaults.
        XCTAssertEqual(result.trendStatus, .consolidation)
        XCTAssertEqual(result.signalScore, 0)
        XCTAssertEqual(result.buySignal, .wait)
    }

    func test_between20And25Bars_macdSkipped_rsiDependsOnCount() {
        // 24 bars: >= RSI_LONG(24) so RSI computes; < MACD_SLOW(26) so MACD is skipped.
        let closes = (0..<24).map { 10.0 + Double($0) * 0.1 }
        let bars = closes.map { DailyBar(date: "d", open: $0, close: $0, high: $0 + 0.1, low: $0 - 0.1, volume: 100) }
        let result = RuleScoreEngine.analyze(bars: bars, code: "600519")

        XCTAssertEqual(result.macdSignal, "数据不足")
        XCTAssertEqual(result.macdDIF, 0, "never computed, stays at RuleScore's default")
        XCTAssertNotEqual(result.rsiSignal, "数据不足", "24 bars satisfies RSI_LONG, RSI should compute")
    }

    func test_fewerThan24Bars_rsiAlsoSkipped() {
        // 22 bars: >= 20 (analyze proceeds) but < RSI_LONG(24) -> RSI skipped too.
        let closes = (0..<22).map { 10.0 + Double($0) * 0.1 }
        let bars = closes.map { DailyBar(date: "d", open: $0, close: $0, high: $0 + 0.1, low: $0 - 0.1, volume: 100) }
        let result = RuleScoreEngine.analyze(bars: bars, code: "600519")

        XCTAssertEqual(result.rsiSignal, "数据不足")
        XCTAssertEqual(result.rsi6, 0)
        XCTAssertEqual(result.rsi12, 0)
        XCTAssertEqual(result.rsi24, 0)
    }

    // MARK: - §0.5-6: MA60 diverges from TechnicalIndicators' MA60 under 60 bars

    func test_ma60_divergesFromTechnicalIndicators_whenUnder60Bars() {
        // Same 40-bar consolidation fixture used above.
        let bars = makeBars(closes: consolidationCloses, highs: consolidationHighs, lows: consolidationLows, volumes: Array(repeating: 10_000, count: 40))

        let ruleScore = RuleScoreEngine.analyze(bars: bars, code: "300059")
        let technicalSeries = TechnicalIndicators.computeAll(bars: bars)

        // RuleScoreEngine: MA60 == MA20 (whole-column fallback) == 15.1125.
        XCTAssertEqual(ruleScore.ma60, 15.1125, accuracy: 1e-6)
        // TechnicalIndicators: MA60 with min_periods=1 == mean of all 40 closes == 14.79375.
        XCTAssertEqual(technicalSeries.ma60.last!, 14.79375, accuracy: 1e-6)

        XCTAssertGreaterThan(
            abs(ruleScore.ma60 - technicalSeries.ma60.last!),
            1e-6,
            "the two MA60 implementations must diverge under 60 bars (§0.5-6)"
        )
    }
}
