import XCTest
@testable import RiseOn

/// Covers task.md S6.1/S6.2's verification points. The expected arrays below
/// are **not hand-computed** — they were generated by actually running the
/// equivalent pandas code (`technical_indicators.py`'s MA/MACD/KDJ/BOLL
/// formulas + `stock_analyzer.py::_calculate_rsi`'s Wilder RSI formula) on
/// this exact 30-bar fixture in a real pandas session, then transcribed
/// verbatim. This is genuine numeric parity, not a guess.
final class TechnicalIndicatorsTests: XCTestCase {

    // MARK: - Fixture (30 bars, deterministic)

    private let closes: [Double] = [10.0, 10.2, 10.15, 10.3, 10.45, 10.4, 10.55, 10.7, 10.65, 10.8, 10.9, 10.85, 11.0, 11.1, 11.05, 10.95, 10.85, 10.9, 11.05, 11.2, 11.15, 11.3, 11.45, 11.4, 11.55, 11.5, 11.65, 11.6, 11.75, 11.9]
    private let highs: [Double] = [10.1, 10.3, 10.25, 10.4, 10.55, 10.5, 10.65, 10.8, 10.75, 10.9, 11.0, 10.95, 11.1, 11.2, 11.15, 11.05, 10.95, 11.0, 11.15, 11.3, 11.25, 11.4, 11.55, 11.5, 11.65, 11.6, 11.75, 11.7, 11.85, 12.0]
    private let lows: [Double] = [9.9, 10.1, 10.05, 10.2, 10.35, 10.3, 10.45, 10.6, 10.55, 10.7, 10.8, 10.75, 10.9, 11.0, 10.95, 10.85, 10.75, 10.8, 10.95, 11.1, 11.05, 11.2, 11.35, 11.3, 11.45, 11.4, 11.55, 11.5, 11.65, 11.8]

    private let expectedMA5: [Double] = [10.0, 10.1, 10.1166666667, 10.1625, 10.22, 10.3, 10.37, 10.48, 10.55, 10.62, 10.72, 10.78, 10.84, 10.93, 10.98, 10.99, 10.99, 10.97, 10.96, 10.99, 11.03, 11.12, 11.23, 11.3, 11.37, 11.44, 11.51, 11.54, 11.61, 11.68]
    private let expectedMA10: [Double] = [10.0, 10.1, 10.1166666667, 10.1625, 10.22, 10.25, 10.2928571429, 10.34375, 10.3777777778, 10.42, 10.51, 10.575, 10.66, 10.74, 10.8, 10.855, 10.885, 10.905, 10.945, 10.985, 11.01, 11.055, 11.1, 11.13, 11.18, 11.235, 11.315, 11.385, 11.455, 11.525]
    private let expectedMA20: [Double] = [10.0, 10.1, 10.1166666667, 10.1625, 10.22, 10.25, 10.2928571429, 10.34375, 10.3777777778, 10.42, 10.4636363636, 10.4958333333, 10.5346153846, 10.575, 10.6066666667, 10.628125, 10.6411764706, 10.6555555556, 10.6763157895, 10.7025, 10.76, 10.815, 10.88, 10.935, 10.99, 11.045, 11.1, 11.145, 11.2, 11.255]
    private let expectedMA60: [Double] = [10.0, 10.1, 10.1166666667, 10.1625, 10.22, 10.25, 10.2928571429, 10.34375, 10.3777777778, 10.42, 10.4636363636, 10.4958333333, 10.5346153846, 10.575, 10.6066666667, 10.628125, 10.6411764706, 10.6555555556, 10.6763157895, 10.7025, 10.7238095238, 10.75, 10.7804347826, 10.80625, 10.836, 10.8615384615, 10.8907407407, 10.9160714286, 10.9448275862, 10.9766666667]
    private let expectedDIF: [Double] = [0.0, 0.015954416, 0.0242838938, 0.0424989104, 0.0682514287, 0.0836615051, 0.1067473313, 0.1355838353, 0.1526428188, 0.176234412, 0.2006866926, 0.2135688305, 0.2331936526, 0.253888956, 0.2632212996, 0.259556084, 0.2457493642, 0.236120175, 0.2378509222, 0.2484621809, 0.2499557633, 0.2602432621, 0.2773033452, 0.283520751, 0.2971267442, 0.3004120466, 0.3115283143, 0.3126988567, 0.3220182405, 0.3376158405]
    private let expectedDEA: [Double] = [0.0, 0.0031908832, 0.0074094853, 0.0144273703, 0.025192182, 0.0368860466, 0.0508583036, 0.0678034099, 0.0847712917, 0.1030639158, 0.1225884711, 0.140784543, 0.1592663649, 0.1781908831, 0.1951969664, 0.2080687899, 0.2156049048, 0.2197079588, 0.2233365515, 0.2283616774, 0.2326804946, 0.2381930481, 0.2460151075, 0.2535162362, 0.2622383378, 0.2698730795, 0.2782041265, 0.2851030725, 0.2924861061, 0.301512053]
    private let expectedMACD: [Double] = [0.0, 0.0255270655, 0.033748817, 0.0561430802, 0.0861184934, 0.093550917, 0.1117780555, 0.1355608507, 0.1357430543, 0.1463409925, 0.1561964429, 0.1455685749, 0.1478545754, 0.1513961458, 0.1360486664, 0.102974588, 0.0602889187, 0.0328244323, 0.0290287414, 0.040201007, 0.0345505374, 0.0441004281, 0.0625764753, 0.0600090296, 0.0697768127, 0.061077934, 0.0666483756, 0.0551915683, 0.0590642687, 0.072207575]
    private let expectedK: [Double] = [50.0, 58.3333333333, 59.7222222222, 66.4814814815, 72.5261158594, 73.9917695473, 78.2167352538, 81.7741197988, 82.2938576437, 84.2743364683, 86.0074523824, 84.4216349216, 85.4477566144, 86.5948007059, 84.3965338039, 76.7771763821, 66.5693996394, 57.7129330929, 60.6975109508, 67.7377345733, 69.4009139579, 74.4724041771, 78.8149361181, 79.6266240787, 82.7140456821, 82.5936775136, 84.2291183424, 82.3432217521, 84.0621478347, 85.2080985565]
    private let expectedD: [Double] = [50.0, 52.7777777778, 55.0925925926, 58.8888888889, 63.4346312124, 66.953677324, 70.7080299673, 74.3967265778, 77.0291035997, 79.4441812226, 81.6319382759, 82.5618371578, 83.52381031, 84.5474737753, 84.4971604515, 81.9238324284, 76.8056881654, 70.4414364745, 67.1934613, 67.3748857244, 68.0502284689, 70.190953705, 73.0656145093, 75.2526176991, 77.7397603601, 79.3577327446, 80.9815279439, 81.4354258799, 82.3109998649, 83.2766994287]
    private let expectedJ: [Double] = [50.0, 69.4444444444, 68.9814814815, 81.6666666667, 90.7090851535, 88.0679539939, 93.2341458267, 96.5289062408, 92.8233657315, 93.9346469597, 94.7584805954, 88.1412304492, 89.2956492232, 90.6894545671, 84.1952805088, 66.4838642896, 46.0968225873, 32.2559263296, 47.7056102525, 68.463432271, 72.102284936, 83.0353051213, 90.3135793355, 88.3746368379, 92.6626163261, 89.0655670515, 90.7242991394, 84.1588134963, 87.5644437744, 89.070896812]
    private let expectedBollUpper: [Double] = [Double.nan, 10.3828427125, 10.3248332666, 10.4125, 10.5561547263, 10.5846640106, 10.6733330353, 10.7986832761, 10.8497711864, 10.9389733455, 11.0347596587, 11.0842956336, 11.163615405, 11.2506762994, 11.3024361961, 11.3218768769, 11.3214662013, 11.3267168747, 11.3532110063, 11.4017288986, 11.402855472, 11.4442016663, 11.4881897211, 11.5208866425, 11.5905260852, 11.6189062825, 11.6848976519, 11.7387392658, 11.8043700505, 11.9046152708]
    private let expectedBollMid: [Double] = [10.0, 10.1, 10.1166666667, 10.1625, 10.22, 10.25, 10.2928571429, 10.34375, 10.3777777778, 10.42, 10.4636363636, 10.4958333333, 10.5346153846, 10.575, 10.6066666667, 10.628125, 10.6411764706, 10.6555555556, 10.6763157895, 10.7025, 10.76, 10.815, 10.88, 10.935, 10.99, 11.045, 11.1, 11.145, 11.2, 11.255]
    private let expectedBollLower: [Double] = [Double.nan, 9.8171572875, 9.9085000667, 9.9125, 9.8838452737, 9.9153359894, 9.9123812504, 9.8888167239, 9.9057843692, 9.9010266545, 9.8925130686, 9.9073710331, 9.9056153642, 9.8993237006, 9.9108971372, 9.9343731231, 9.9608867399, 9.9843942364, 9.9994205727, 10.0032711014, 10.117144528, 10.1857983337, 10.2718102789, 10.3491133575, 10.3894739148, 10.4710937175, 10.5151023481, 10.5512607342, 10.5956299495, 10.6053847292]
    private let expectedRSI6: [Double] = [50.0, 100.0, 76.9230769231, 87.3949579832, 91.8389553863, 80.4882700744, 86.4964756197, 90.1399110953, 81.359183165, 86.1989795892, 88.5725470703, 80.287593545, 85.2533619791, 87.7267695887, 79.7055150922, 65.3622400146, 53.7543163461, 58.2075612653, 68.9659334562, 76.2901207121, 69.7094189863, 76.8868060665, 82.0038543077, 75.3326705588, 80.9204501021, 74.1974076633, 80.1380346484, 73.3801962382, 79.5794460271, 84.0396758713]
    private let expectedRSI12: [Double] = [50.0, 100.0, 78.5714285714, 87.4045801527, 91.31163236, 82.0558445114, 86.5257759755, 89.4049578008, 82.9588803873, 86.2122725721, 87.8932543802, 82.4127172652, 85.3934614359, 86.9963013747, 82.0832003765, 73.0786141289, 65.2677885478, 67.1811147866, 72.1941678669, 76.1657890464, 72.4050920962, 76.2438769614, 79.3740437425, 75.7448326562, 78.9019192148, 75.3361522653, 78.5139852801, 75.000008705, 78.1940252428, 80.8614646483]
    private let expectedRSI24: [Double] = [50.0, 100.0, 79.3103448276, 87.4431301183, 91.0955253191, 82.7260049248, 86.5844799976, 89.1203227771, 83.6223886413, 86.2732917049, 87.6624862874, 83.2658839806, 85.5366706483, 86.7842220271, 83.0468466393, 76.1984994868, 70.161195972, 71.3457085441, 74.512958566, 77.1486139603, 74.4699846483, 76.9728076525, 79.1098093685, 76.6360406562, 78.7191950802, 76.3513467728, 78.3865251821, 76.1083326072, 78.1007609199, 79.8538787008]

    private func makeBars() -> [DailyBar] {
        (0..<closes.count).map { i in
            DailyBar(
                date: String(format: "2024-06-%02d", i + 1),
                open: closes[i],
                close: closes[i],
                high: highs[i],
                low: lows[i],
                volume: 10_000
            )
        }
    }

    /// Element-wise comparison with `NaN`-aware equality: both `NaN` at the
    /// same index passes (mirrors pandas leaving early-window BOLL as NaN);
    /// only one side being `NaN` fails.
    private func assertParity(
        _ actual: [Double],
        _ expected: [Double],
        _ label: String,
        accuracy: Double = 1e-6,
        file: StaticString = #file,
        line: UInt = #line
    ) {
        XCTAssertEqual(actual.count, expected.count, "\(label): count mismatch", file: file, line: line)
        for i in 0..<min(actual.count, expected.count) {
            if expected[i].isNaN {
                XCTAssertTrue(actual[i].isNaN, "\(label)[\(i)]: expected NaN, got \(actual[i])", file: file, line: line)
            } else {
                XCTAssertEqual(actual[i], expected[i], accuracy: accuracy, "\(label)[\(i)]", file: file, line: line)
            }
        }
    }

    // MARK: - Parity tests

    func test_movingAverages_matchPandasMinPeriods1() {
        let mas = TechnicalIndicators.movingAverages(closes: closes)
        assertParity(mas[5] ?? [], expectedMA5, "MA5")
        assertParity(mas[10] ?? [], expectedMA10, "MA10")
        assertParity(mas[20] ?? [], expectedMA20, "MA20")
        assertParity(mas[60] ?? [], expectedMA60, "MA60")
    }

    func test_macd_matchesPandasEwmAdjustFalse() {
        let (dif, dea, macd) = TechnicalIndicators.macd(closes: closes)
        assertParity(dif, expectedDIF, "DIF")
        assertParity(dea, expectedDEA, "DEA")
        assertParity(macd, expectedMACD, "MACD")
    }

    func test_kdj_matchesPandasComBasedEwm() {
        let (k, d, j) = TechnicalIndicators.kdj(highs: highs, lows: lows, closes: closes)
        assertParity(k, expectedK, "K")
        assertParity(d, expectedD, "D")
        assertParity(j, expectedJ, "J")
    }

    func test_bollingerBands_matchPandasSampleStd() {
        let (upper, mid, lower) = TechnicalIndicators.bollingerBands(closes: closes)
        assertParity(upper, expectedBollUpper, "BOLL_UPPER")
        assertParity(mid, expectedBollMid, "BOLL_MID")
        assertParity(lower, expectedBollLower, "BOLL_LOWER")
    }

    func test_rsiWilder_matchesStockAnalyzerPy_period6_12_24() {
        assertParity(TechnicalIndicators.rsiWilder(closes: closes, period: 6), expectedRSI6, "RSI6")
        assertParity(TechnicalIndicators.rsiWilder(closes: closes, period: 12), expectedRSI12, "RSI12")
        assertParity(TechnicalIndicators.rsiWilder(closes: closes, period: 24), expectedRSI24, "RSI24")
    }

    /// Regression guard for §0.5-2: the banned simple-average RSI would
    /// produce different numbers than Wilder's EMA on the same data. This
    /// doesn't test a simple-average implementation (there isn't one — it
    /// was never ported), it just confirms Wilder's RSI is *not* accidentally
    /// equal to a naive rolling-mean RSI on this fixture, as a sanity check
    /// that the EMA recursion is actually being used.
    func test_rsiWilder_isNotASimpleRollingMeanRSI() {
        let wilder = TechnicalIndicators.rsiWilder(closes: closes, period: 12)

        // Naive rolling-mean RSI(12), computed independently right here
        // (not shared code with the production implementation) purely to
        // prove the two formulas diverge on this data.
        var gains = [Double](repeating: 0, count: closes.count)
        var losses = [Double](repeating: 0, count: closes.count)
        for i in 1..<closes.count {
            let delta = closes[i] - closes[i - 1]
            gains[i] = delta > 0 ? delta : 0
            losses[i] = delta < 0 ? -delta : 0
        }
        let period = 12
        var naive = [Double](repeating: 50, count: closes.count)
        for i in 0..<closes.count {
            let start = max(0, i - period + 1)
            let avgGain = gains[start...i].reduce(0, +) / Double(i - start + 1)
            let avgLoss = losses[start...i].reduce(0, +) / Double(i - start + 1)
            if avgLoss != 0 {
                naive[i] = 100 - 100 / (1 + avgGain / avgLoss)
            }
        }

        var anyDifferent = false
        for i in 0..<closes.count where abs(wilder[i] - naive[i]) > 1e-6 {
            anyDifferent = true
            break
        }
        XCTAssertTrue(anyDifferent, "Wilder RSI and a naive rolling-mean RSI should diverge on this fixture")
    }

    // MARK: - S6.2 latest signals

    func test_latestSignals_emptyBars_returnsNil() {
        XCTAssertNil(TechnicalIndicators.latestSignals(bars: [], series: TechnicalIndicators.computeAll(bars: [])))
    }

    func test_latestSignals_onFullFixture_matchesHandCheckedExpectations() {
        let bars = makeBars()
        let series = TechnicalIndicators.computeAll(bars: bars)
        guard let signals = TechnicalIndicators.latestSignals(bars: bars, series: series) else {
            return XCTFail("expected non-nil signals for non-empty bars")
        }

        // Cross-checked directly against the reference arrays above at the
        // last index (29) and second-to-last (28):
        // DIF[29]=0.3376 > DEA[29]=0.3015 and DIF[28]=0.3220 > DEA[28]=0.2925 -> no golden cross (already above)
        XCTAssertFalse(signals.macdGoldenCross)
        XCTAssertFalse(signals.macdDeadCross)
        XCTAssertTrue(signals.macdHistogramPositive, "MACD[29]=0.0722 > 0")

        // K[29]=85.21 > D[29]=83.28, K[28]=84.06 > D[28]=82.31 -> already above, no fresh cross
        XCTAssertFalse(signals.kdjGoldenCross)
        XCTAssertFalse(signals.kdjDeadCross)
        XCTAssertTrue(signals.kdjOverbought, "K[29]=85.2 > 80 and D[29]=83.3 > 80")
        XCTAssertFalse(signals.kdjOversold)

        XCTAssertTrue(signals.rsi6Overbought, "RSI6[29]=84.04 > 80")
        XCTAssertFalse(signals.rsi6Oversold)
        XCTAssertTrue(signals.rsi12Overbought, "RSI12[29]=80.86 > 70")
        XCTAssertFalse(signals.rsi12Oversold)

        XCTAssertFalse(signals.priceAboveUpper, "close[29]=11.90 < BOLL_UPPER[29]=11.905")
        XCTAssertFalse(signals.priceBelowLower)
        XCTAssertFalse(signals.bollSqueeze)

        XCTAssertTrue(signals.ma5AboveMa20, "MA5[29]=11.68 > MA20[29]=11.255")
        XCTAssertTrue(signals.ma10AboveMa20, "MA10[29]=11.525 > MA20[29]=11.255")
        XCTAssertTrue(signals.priceAboveMa60, "close[29]=11.90 > MA60[29]=10.977")
    }

    /// Explicitly exercises every boolean's true AND false branch (task.md
    /// S6.2's verification point), using small hand-built series rather than
    /// the big fixture so each case is obvious and isolated.
    func test_latestSignals_everyBranch_trueAndFalse() {
        func series(dif: [Double], dea: [Double], macd: [Double], k: [Double], d: [Double],
                    rsi6: [Double], rsi12: [Double], upper: [Double], mid: [Double], lower: [Double],
                    ma5: [Double], ma20: [Double], ma60: [Double]) -> TechnicalIndicators.Series {
            TechnicalIndicators.Series(
                ma5: ma5, ma10: ma5, ma20: ma20, ma60: ma60,
                dif: dif, dea: dea, macd: macd,
                k: k, d: d, j: Array(repeating: 0, count: dif.count),
                rsi6: rsi6, rsi12: rsi12, rsi24: rsi6,
                bollUpper: upper, bollMid: mid, bollLower: lower
            )
        }
        let bars = [
            DailyBar(date: "d0", open: 10, close: 10, high: 10, low: 10, volume: 1),
            DailyBar(date: "d1", open: 10, close: 10, high: 10, low: 10, volume: 1),
        ]

        // --- MACD golden/dead cross: true branch ---
        var s = series(
            dif: [-0.1, 0.1], dea: [0.0, 0.0], macd: [-0.2, 0.2],
            k: [50, 50], d: [50, 50], rsi6: [50, 50], rsi12: [50, 50],
            upper: [100, 100], mid: [10, 10], lower: [0, 0], ma5: [10, 10], ma20: [10, 10], ma60: [10, 10]
        )
        var signals = TechnicalIndicators.latestSignals(bars: bars, series: s)!
        XCTAssertTrue(signals.macdGoldenCross)
        XCTAssertTrue(signals.macdHistogramPositive)
        XCTAssertFalse(signals.macdDeadCross)

        // --- MACD dead cross: true branch ---
        s = series(
            dif: [0.1, -0.1], dea: [0.0, 0.0], macd: [0.2, -0.2],
            k: [50, 50], d: [50, 50], rsi6: [50, 50], rsi12: [50, 50],
            upper: [100, 100], mid: [10, 10], lower: [0, 0], ma5: [10, 10], ma20: [10, 10], ma60: [10, 10]
        )
        signals = TechnicalIndicators.latestSignals(bars: bars, series: s)!
        XCTAssertTrue(signals.macdDeadCross)
        XCTAssertFalse(signals.macdHistogramPositive)
        XCTAssertFalse(signals.macdGoldenCross)

        // --- KDJ golden/dead cross + overbought/oversold ---
        s = series(
            dif: [0, 0], dea: [0, 0], macd: [0, 0],
            k: [40, 85], d: [45, 82], rsi6: [50, 50], rsi12: [50, 50],
            upper: [100, 100], mid: [10, 10], lower: [0, 0], ma5: [10, 10], ma20: [10, 10], ma60: [10, 10]
        )
        signals = TechnicalIndicators.latestSignals(bars: bars, series: s)!
        XCTAssertTrue(signals.kdjGoldenCross)
        XCTAssertTrue(signals.kdjOverbought)
        XCTAssertFalse(signals.kdjDeadCross)
        XCTAssertFalse(signals.kdjOversold)

        s = series(
            dif: [0, 0], dea: [0, 0], macd: [0, 0],
            k: [85, 15], d: [82, 18], rsi6: [50, 50], rsi12: [50, 50],
            upper: [100, 100], mid: [10, 10], lower: [0, 0], ma5: [10, 10], ma20: [10, 10], ma60: [10, 10]
        )
        signals = TechnicalIndicators.latestSignals(bars: bars, series: s)!
        XCTAssertTrue(signals.kdjDeadCross)
        XCTAssertTrue(signals.kdjOversold)
        XCTAssertFalse(signals.kdjGoldenCross)
        XCTAssertFalse(signals.kdjOverbought)

        // --- RSI overbought/oversold thresholds (6 uses 80/20, 12 uses 70/30) ---
        s = series(
            dif: [0, 0], dea: [0, 0], macd: [0, 0],
            k: [50, 50], d: [50, 50], rsi6: [50, 85], rsi12: [50, 75],
            upper: [100, 100], mid: [10, 10], lower: [0, 0], ma5: [10, 10], ma20: [10, 10], ma60: [10, 10]
        )
        signals = TechnicalIndicators.latestSignals(bars: bars, series: s)!
        XCTAssertTrue(signals.rsi6Overbought)
        XCTAssertTrue(signals.rsi12Overbought)
        XCTAssertFalse(signals.rsi6Oversold)
        XCTAssertFalse(signals.rsi12Oversold)

        s = series(
            dif: [0, 0], dea: [0, 0], macd: [0, 0],
            k: [50, 50], d: [50, 50], rsi6: [50, 15], rsi12: [50, 25],
            upper: [100, 100], mid: [10, 10], lower: [0, 0], ma5: [10, 10], ma20: [10, 10], ma60: [10, 10]
        )
        signals = TechnicalIndicators.latestSignals(bars: bars, series: s)!
        XCTAssertTrue(signals.rsi6Oversold)
        XCTAssertTrue(signals.rsi12Oversold)
        XCTAssertFalse(signals.rsi6Overbought)
        XCTAssertFalse(signals.rsi12Overbought)

        // --- BOLL breakout + squeeze ---
        let barsAbove = [
            DailyBar(date: "d0", open: 10, close: 10, high: 10, low: 10, volume: 1),
            DailyBar(date: "d1", open: 20, close: 20, high: 20, low: 20, volume: 1),
        ]
        s = series(
            dif: [0, 0], dea: [0, 0], macd: [0, 0],
            k: [50, 50], d: [50, 50], rsi6: [50, 50], rsi12: [50, 50],
            upper: [100, 15], mid: [10, 10], lower: [0, 5], ma5: [10, 10], ma20: [10, 10], ma60: [10, 10]
        )
        signals = TechnicalIndicators.latestSignals(bars: barsAbove, series: s)!
        XCTAssertTrue(signals.priceAboveUpper, "close 20 > upper 15")
        XCTAssertFalse(signals.priceBelowLower)

        let barsBelow = [
            DailyBar(date: "d0", open: 10, close: 10, high: 10, low: 10, volume: 1),
            DailyBar(date: "d1", open: 2, close: 2, high: 2, low: 2, volume: 1),
        ]
        s = series(
            dif: [0, 0], dea: [0, 0], macd: [0, 0],
            k: [50, 50], d: [50, 50], rsi6: [50, 50], rsi12: [50, 50],
            upper: [100, 15], mid: [10, 10], lower: [0, 5], ma5: [10, 10], ma20: [10, 10], ma60: [10, 10]
        )
        signals = TechnicalIndicators.latestSignals(bars: barsBelow, series: s)!
        XCTAssertTrue(signals.priceBelowLower, "close 2 < lower 5")
        XCTAssertFalse(signals.priceAboveUpper)

        // squeeze: (upper-lower)/mid < 0.1
        s = series(
            dif: [0, 0], dea: [0, 0], macd: [0, 0],
            k: [50, 50], d: [50, 50], rsi6: [50, 50], rsi12: [50, 50],
            upper: [100, 10.4], mid: [10, 10], lower: [0, 9.7], ma5: [10, 10], ma20: [10, 10], ma60: [10, 10]
        )
        signals = TechnicalIndicators.latestSignals(bars: bars, series: s)!
        XCTAssertTrue(signals.bollSqueeze, "(10.4-9.7)/10 = 0.07 < 0.1")

        s = series(
            dif: [0, 0], dea: [0, 0], macd: [0, 0],
            k: [50, 50], d: [50, 50], rsi6: [50, 50], rsi12: [50, 50],
            upper: [100, 12], mid: [10, 10], lower: [0, 8], ma5: [10, 10], ma20: [10, 10], ma60: [10, 10]
        )
        signals = TechnicalIndicators.latestSignals(bars: bars, series: s)!
        XCTAssertFalse(signals.bollSqueeze, "(12-8)/10 = 0.4, not < 0.1")

        // --- MA crosses ---
        s = series(
            dif: [0, 0], dea: [0, 0], macd: [0, 0],
            k: [50, 50], d: [50, 50], rsi6: [50, 50], rsi12: [50, 50],
            upper: [100, 100], mid: [10, 10], lower: [0, 0], ma5: [10, 12], ma20: [10, 10], ma60: [10, 8]
        )
        signals = TechnicalIndicators.latestSignals(bars: bars, series: s)!
        XCTAssertTrue(signals.ma5AboveMa20, "12 > 10")
        XCTAssertTrue(signals.priceAboveMa60, "close 10 > MA60 8")

        s = series(
            dif: [0, 0], dea: [0, 0], macd: [0, 0],
            k: [50, 50], d: [50, 50], rsi6: [50, 50], rsi12: [50, 50],
            upper: [100, 100], mid: [10, 10], lower: [0, 0], ma5: [10, 8], ma20: [10, 10], ma60: [10, 15]
        )
        signals = TechnicalIndicators.latestSignals(bars: bars, series: s)!
        XCTAssertFalse(signals.ma5AboveMa20, "8 not > 10")
        XCTAssertFalse(signals.priceAboveMa60, "close 10 not > MA60 15")
    }

    func test_latestSignals_singleBar_crossSignalsAreFalse() {
        // len(df) == 1 -> prev == latest in Python too, so a cross can never
        // be detected (can't be both `>` and `<=` against itself).
        let bars = [DailyBar(date: "d0", open: 10, close: 10, high: 10.5, low: 9.5, volume: 100)]
        let series = TechnicalIndicators.computeAll(bars: bars)
        let signals = TechnicalIndicators.latestSignals(bars: bars, series: series)!

        XCTAssertFalse(signals.macdGoldenCross)
        XCTAssertFalse(signals.macdDeadCross)
        XCTAssertFalse(signals.kdjGoldenCross)
        XCTAssertFalse(signals.kdjDeadCross)
    }
}
